sz1521/js13kgames2019

- .editorconfig
- .gitignore
- LICENSE
- README.md
- package-lock.json
- package.json
- postbuild.js
- src/index.html
- src/main.js
- webpack.common.js
- webpack.dev.js
- webpack.prod.js
> Project structure

- .eslintrc.json
- package-lock.json
- package.json
- postbuild.js
- src/main.js
- webpack.common.js
- webpack.dev.js
- webpack.prod.js
Basic configuration for eslint and a simple scene for the game.
> More project structure

- src/index.html
- src/main.js
Full window canvas. 
Resizing functionality.
Functions changed to arrow functions.
> Full window canvas

- src/main.js
Jumping and climbing controls.
> Controls with physics

- src/main.js
Still needs some better start position to make it look more real clouds that looks like they are continuing.
> Two layered clouds

- src/images/house.svg
- src/images/player.svg
- src/main.js
- webpack.dev.js
A simple loading of SVG images.
> Svg images

- package-lock.json
- package.json
- src/main.js
- webpack.common.js
Using svg-inline-loader to bundle images.
> SVG images are bundled with webpack.

- src/enemy.js
- src/main.js
Rolling back time when space is held down. Both enemies and clouds move back to where they came from.
> Roll back time

- src/camera.js
- src/main.js
- src/player.js
When hitting an enemy, the player turns horizontal and there is a screen shake effect when hitting the ground.
> Falling animation

- src/main.js
Enter key to start game. Very minimal implementation.
> Basic implementation for start key for the game.

- src/images/player-vertical.svg
- src/main.js
- src/player.js
Needs way to switch svg for climbing.
Start screen centering.
> Player animation for left, svg for climbing

- src/player.js
Player size adjusted so that it won't hit enemies going in above levels.
> Player size smaller.

- src/main.js
- src/player.js
- src/utils.js
> Svg load function to util file (move other similars?). 

- src/main.js
- src/player.js
Bigger level with two buildings, anti-gravity goes off when using too much time-travel.
> Level design

- src/camera.js
- src/drone.js
- src/main.js
- src/player.js
- src/utils.js
Enemies hit the player, instead of dying instantly. Drone enemies added.
> More level design

- src/images/house.svg
- src/main.js
Optimized clouds code.
Basic city landscape. 
Sky gradient.
> Advanced gfx

- src/main.js
- src/music.js
- src/player.js
- loading screen complete when music fully loaded
- player can restart the level by pressing enter
> Game states

- src/main.js
> Ladders and platform changes

- src/main.js
- src/player.js
- src/portal.js
- A portal which is the target of the game
- Anti-gravity works by holding the key down
- Help texts at the start
- Made the game somewhat easier
- Graphical effect for time-travel
> Start and end

- src/drone.js
- src/enemy.js
- src/images/drone.svg
- src/images/droneFollow.svg
- src/main.js
Small border lines for building background.
Follow visuals for drones. Enemy speeds varies.
> Gfx finalization

- src/main.js
- possibility to have several levels
- start screen is level 0 with a separate game loop (prevents blank screen when resizing window)
> Many levels
